# Generated by Django 6.0.6 on 2026-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
