# Generated by Django 6.0.6 on 2026-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, help_text='Optional live demo URL'),
        ),
    ]
